import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import AdminNav from "@/components/admin/admin-nav";
import { deleteBandMember, saveBandMember } from "./actions";

type Props = { searchParams: Promise<{ edit?: string; saved?: string; error?: string }> };
export default async function BandPage({ searchParams }: Props) {
  const query = await searchParams;
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/admin/login");
  const { data: members, error } = await supabase.from("band_members").select("*").order("sort_order").order("name");
  const editing = (members ?? []).find((m) => m.id === query.edit);
  const activeSplit = (members ?? []).filter((m) => m.active).reduce((sum, m) => sum + Number(m.default_split_percent), 0);
  return <main className="min-h-screen bg-stone-950 px-4 py-8 text-stone-100 sm:px-6"><div className="mx-auto max-w-6xl">
    <header className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.3em] text-red-500">Pocket Fuzz</p><h1 className="mt-2 text-4xl font-black uppercase">Band Roster</h1></div><AdminNav /></header>
    {query.saved ? <Notice>Band roster updated.</Notice> : null}{query.error || error ? <ErrorBox>{query.error || error?.message}</ErrorBox> : null}
    <section className="mt-8 grid gap-4 sm:grid-cols-3"><Kpi label="Members" value={String((members ?? []).length)} /><Kpi label="Active" value={String((members ?? []).filter(m=>m.active).length)} /><Kpi label="Default Split Total" value={`${activeSplit.toFixed(2)}%`} warning={Math.abs(activeSplit-100)>.02} /></section>
    <section className="mt-8 rounded-2xl border border-stone-800 bg-stone-900 p-6"><h2 className="text-xl font-black uppercase">{editing ? "Edit Member" : "Add Member"}</h2><form action={saveBandMember} className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{editing ? <input type="hidden" name="id" value={editing.id}/> : null}<Field name="name" label="Name" value={editing?.name} required/><Field name="instrument" label="Instrument" value={editing?.instrument}/><Field name="email" label="Email" type="email" value={editing?.email}/><Field name="phone" label="Phone" value={editing?.phone}/><Field name="venmo_handle" label="Venmo" value={editing?.venmo_handle}/><Field name="default_split_percent" label="Default Split %" type="number" step="0.001" min="0" value={String(editing?.default_split_percent ?? 0)}/><Field name="sort_order" label="Sort Order" type="number" step="1" value={String(editing?.sort_order ?? 0)}/><label className="flex items-center gap-3 rounded-lg border border-stone-700 bg-stone-950 px-4 py-3"><input type="checkbox" name="active" defaultChecked={editing?.active ?? true}/><span className="font-semibold">Active member</span></label><div className="md:col-span-2 xl:col-span-4"><label className="mb-2 block text-sm font-semibold">Notes</label><textarea name="notes" defaultValue={editing?.notes ?? ""} rows={3} className="w-full rounded-lg border border-stone-700 bg-stone-950 px-4 py-3"/></div><button className="rounded-lg bg-red-600 px-5 py-3 font-black uppercase hover:bg-red-500">{editing ? "Save Member" : "Add Member"}</button></form></section>
    <section className="mt-8 overflow-hidden rounded-2xl border border-stone-800 bg-stone-900"><div className="border-b border-stone-800 p-6"><h2 className="text-xl font-black uppercase">Members</h2></div><div className="divide-y divide-stone-800">{(members ?? []).map(m=><article key={m.id} className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-3"><h3 className="font-black">{m.name}</h3><span className={`rounded-full border px-2 py-1 text-[10px] font-black uppercase ${m.active?"border-emerald-800 text-emerald-300":"border-stone-700 text-stone-500"}`}>{m.active?"Active":"Inactive"}</span></div><p className="mt-1 text-sm text-stone-400">{m.instrument || "No instrument"} · {Number(m.default_split_percent).toFixed(2)}% · {m.venmo_handle || "No Venmo"}</p></div><div className="flex gap-3"><a href={`/admin/band?edit=${m.id}`} className="rounded-lg border border-stone-700 px-4 py-2 text-sm font-bold">Edit</a><form action={deleteBandMember}><input type="hidden" name="id" value={m.id}/><button className="rounded-lg border border-red-900 px-4 py-2 text-sm font-bold text-red-300">Delete</button></form></div></article>)}{!members?.length?<p className="p-10 text-center text-stone-500">No band members yet.</p>:null}</div></section>
  </div></main>;
}
function Field({name,label,type="text",value,step,min,required=false}:{name:string;label:string;type?:string;value?:string|null;step?:string;min?:string;required?:boolean}){return <div><label className="mb-2 block text-sm font-semibold">{label}</label><input name={name} type={type} defaultValue={value ?? ""} step={step} min={min} required={required} className="w-full rounded-lg border border-stone-700 bg-stone-950 px-4 py-3"/></div>}
function Kpi({label,value,warning=false}:{label:string;value:string;warning?:boolean}){return <div className={`rounded-xl border p-5 ${warning?"border-amber-800 bg-amber-950/30":"border-stone-800 bg-stone-900"}`}><p className="text-xs font-bold uppercase text-stone-500">{label}</p><p className="mt-2 text-2xl font-black">{value}</p></div>}
function Notice({children}:{children:React.ReactNode}){return <div className="mt-6 rounded-lg border border-emerald-900 bg-emerald-950/30 p-4 text-emerald-200">{children}</div>}
function ErrorBox({children}:{children:React.ReactNode}){return <div className="mt-6 rounded-lg border border-red-900 bg-red-950/30 p-4 text-red-200">{children}</div>}
